### ISSUE TITLE
Cannot convert a Symbol value to a string

### ISSUE THREAD

**Issue by chadhietala** [emberjs/emberjs-build#87]
When I run `npm test` on ember I get the following error.

```
Cannot convert a Symbol value to a string
TypeError: Cannot convert a Symbol value to a string
    at RegExp.test (native)
    at Symbol.hasOwnProperty (/Users/chietala/workspace/ember.js/node_modules/emberjs-build/node_modules/es6-module-transpiler/dist/es6-module-transpiler.js:163:43)
    at /Users/chietala/workspace/ember.js/node_modules/emberjs-build/node_modules/babel-core/node_modules/core-js/library.js:133:17
    at setToStringTag (/Users/chietala/workspace/ember.js/node_modules/emberjs-build/node_modules/babel-core/node_modules/core-js/library.js:89:13)
    at /Users/chietala/workspace/ember.js/node_modules/emberjs-build/node_modules/babel-core/node_modules/core-js/library.js:652:3
    at /Users/chietala/workspace/ember.js/node_modules/emberjs-build/node_modules/babel-core/node_modules/core-js/library.js:673:2
    at Object.<anonymous> (/Users/chietala/workspace/ember.js/node_modules/emberjs-build/node_modules/babel-core/node_modules/core-js/library.js:2339:2)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
npm ERR! Test failed.  See above for more details.
```

__System Info__

Node: 0.12.0
NPM 2.7.0
zlib: 1.2.8
uv: 1.0.2

I believe this is related to the node version. Reporting now because Ember CLI 0.2.0 warns about bumping the node version.

**Comment by rwjblue** [comment]
You cannot use Node v0.12 or iojs at the moment.  We need to remove the old es6-module-transpiler to fix this issue, but we are blocked on https://github.com/ebryn/backburner.js/issues/128 being fixed first.  I submitted https://github.com/emberjs/emberjs-build/pull/84 which contains much of the internal work to remove it, and I believe that @stefanpenner was working on fixing the backburner issue.

**Comment by stefanpenner** [comment]
it will be fixed tonight!

**Comment by seanpdoyle** [comment]
@stefanpenner what is the status on this? 

Is there anything that needs an extra set of eyes?

**Comment by stefanpenner** [comment]
each micro libs needs updating:

I started making progress, but have been pulled in other directions for now.

- [ ] https://github.com/ebryn/backburner.js/pull/129
- [ ] github.com/krisselden/dag-map
